-- Radiology Report Teaching Atlas cloud schema
-- Store only de-identified teaching content. Keep source videos outside Supabase.

create table if not exists public.atlas_cases (
  record_id text primary key,
  card_id text not null,
  lecture_date date not null,
  source_video text not null default '',
  storage_path text not null default '',
  metadata jsonb not null default '{}'::jsonb,
  subtitle text not null default '',
  transcript text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.atlas_teaching_sets (
  id bigint generated by default as identity primary key,
  name text not null,
  description text not null default '',
  card_ids text[] not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists atlas_cases_metadata_gin
  on public.atlas_cases using gin (metadata);

create index if not exists atlas_cases_lecture_date_card_id
  on public.atlas_cases (lecture_date desc, card_id);

create or replace function public.set_atlas_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists atlas_cases_updated_at on public.atlas_cases;
create trigger atlas_cases_updated_at
before update on public.atlas_cases
for each row execute function public.set_atlas_updated_at();

drop trigger if exists atlas_teaching_sets_updated_at on public.atlas_teaching_sets;
create trigger atlas_teaching_sets_updated_at
before update on public.atlas_teaching_sets
for each row execute function public.set_atlas_updated_at();

alter table public.atlas_cases enable row level security;
alter table public.atlas_teaching_sets enable row level security;

revoke all on public.atlas_cases from anon, authenticated;
revoke all on public.atlas_teaching_sets from anon, authenticated;
grant select, insert, update on public.atlas_cases to anon, authenticated;
grant select, insert, update on public.atlas_teaching_sets to anon, authenticated;
grant usage, select on sequence public.atlas_teaching_sets_id_seq to anon, authenticated;

drop policy if exists "atlas cases are readable" on public.atlas_cases;
create policy "atlas cases are readable"
on public.atlas_cases for select
to anon, authenticated
using (true);

drop policy if exists "atlas cases can be inserted" on public.atlas_cases;
create policy "atlas cases can be inserted"
on public.atlas_cases for insert
to anon, authenticated
with check (record_id <> '' and card_id <> '' and jsonb_typeof(metadata) = 'object');

drop policy if exists "atlas cases can be updated" on public.atlas_cases;
create policy "atlas cases can be updated"
on public.atlas_cases for update
to anon, authenticated
using (true)
with check (record_id <> '' and card_id <> '' and jsonb_typeof(metadata) = 'object');

drop policy if exists "atlas teaching sets are readable" on public.atlas_teaching_sets;
create policy "atlas teaching sets are readable"
on public.atlas_teaching_sets for select
to anon, authenticated
using (true);

drop policy if exists "atlas teaching sets can be inserted" on public.atlas_teaching_sets;
create policy "atlas teaching sets can be inserted"
on public.atlas_teaching_sets for insert
to anon, authenticated
with check (name <> '' and cardinality(card_ids) > 0);

drop policy if exists "atlas teaching sets can be updated" on public.atlas_teaching_sets;
create policy "atlas teaching sets can be updated"
on public.atlas_teaching_sets for update
to anon, authenticated
using (true)
with check (name <> '' and cardinality(card_ids) > 0);
